from tibiapy.parsers.bazaar import *
from tibiapy.parsers.character import *
from tibiapy.parsers.creature import *
from tibiapy.parsers.event import *
from tibiapy.parsers.fansite import *
from tibiapy.parsers.forum import *
from tibiapy.parsers.guild import *
from tibiapy.parsers.highscores import *
from tibiapy.parsers.house import *
from tibiapy.parsers.kill_statistics import *
from tibiapy.parsers.leaderboard import *
from tibiapy.parsers.news import *
from tibiapy.parsers.spell import *
from tibiapy.parsers.world import *
