name: 🔎 Analyze
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: 🧪 Test & Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚚
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Set up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install dependencies ⚙️
        run: |
          python -m pip install --upgrade pip
          pip install -U -e .[testing,linting]
      - name: Test with Coverage 🔧
        run: |
          coverage run
      - name: Anaylze with Ruff ⚡️
        run: ruff check --output-format json --output-file ruff.json --exit-zero .
      - name: Generate Coverage Reports 📋
        run: |
          coverage report
          coverage xml
      - name: Upload reports 📤
        uses: actions/upload-artifact@v7
        with:
          name: reports
          path: |
            ruff.json
            coverage.xml
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 🚚
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Download reports 📥
        uses: actions/download-artifact@v8
        with:
          name: reports
      - name: SonarCloud Scan ☁️
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
