name: Coverage Report
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -e .[test]
      - name: Test
        run: |
          coverage run setup.py test
      - name: Coverage Report
        run: |
          coverage report
          coverage xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1